const BATTLE_DETAIL = 'BATTLE_DETAIL';
const BATTLE_LIST = 'BATTLE_LIST';
const CREATE_BATTLE = 'CREATE_BATTLE';
const SELECT_TEAM = 'SELECT_TEAM';

export { BATTLE_DETAIL, BATTLE_LIST, CREATE_BATTLE, SELECT_TEAM };
