const BATTLE_DETAIL = 'BATTLE_DETAIL';
const BATTLE_LIST = 'BATTLE_LIST';
const SELECT_TEAM = 'SELECT_TEAM';
const POKEMON_LIST = 'POKEMON_LIST';

export { BATTLE_DETAIL, POKEMON_LIST, BATTLE_LIST, SELECT_TEAM };
