# Generated by Django 2.2.19 on 2021-03-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='creator_pokemon_1',
            field=models.CharField(choices=[('bulbasaur', 'bulbasaur'), ('ivysaur', 'ivysaur'), ('venusaur', 'venusaur'), ('charmander', 'charmander'), ('charmeleon', 'charmeleon'), ('charizard', 'charizard'), ('squirtle', 'squirtle'), ('wartortle', 'wartortle'), ('blastoise', 'blastoise'), ('caterpie', 'caterpie'), ('metapod', 'metapod'), ('butterfree', 'butterfree'), ('weedle', 'weedle'), ('kakuna', 'kakuna'), ('beedrill', 'beedrill'), ('pidgey', 'pidgey'), ('pidgeotto', 'pidgeotto'), ('pidgeot', 'pidgeot'), ('rattata', 'rattata'), ('raticate', 'raticate')], max_length=200, null=True, verbose_name='creator_pokemon_1'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='creator_pokemon_2',
            field=models.CharField(choices=[('bulbasaur', 'bulbasaur'), ('ivysaur', 'ivysaur'), ('venusaur', 'venusaur'), ('charmander', 'charmander'), ('charmeleon', 'charmeleon'), ('charizard', 'charizard'), ('squirtle', 'squirtle'), ('wartortle', 'wartortle'), ('blastoise', 'blastoise'), ('caterpie', 'caterpie'), ('metapod', 'metapod'), ('butterfree', 'butterfree'), ('weedle', 'weedle'), ('kakuna', 'kakuna'), ('beedrill', 'beedrill'), ('pidgey', 'pidgey'), ('pidgeotto', 'pidgeotto'), ('pidgeot', 'pidgeot'), ('rattata', 'rattata'), ('raticate', 'raticate')], max_length=200, null=True, verbose_name='creator_pokemon_2'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='creator_pokemon_3',
            field=models.CharField(choices=[('bulbasaur', 'bulbasaur'), ('ivysaur', 'ivysaur'), ('venusaur', 'venusaur'), ('charmander', 'charmander'), ('charmeleon', 'charmeleon'), ('charizard', 'charizard'), ('squirtle', 'squirtle'), ('wartortle', 'wartortle'), ('blastoise', 'blastoise'), ('caterpie', 'caterpie'), ('metapod', 'metapod'), ('butterfree', 'butterfree'), ('weedle', 'weedle'), ('kakuna', 'kakuna'), ('beedrill', 'beedrill'), ('pidgey', 'pidgey'), ('pidgeotto', 'pidgeotto'), ('pidgeot', 'pidgeot'), ('rattata', 'rattata'), ('raticate', 'raticate')], max_length=200, null=True, verbose_name='creator_pokemon_3'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='opponent_pokemon_1',
            field=models.CharField(choices=[('bulbasaur', 'bulbasaur'), ('ivysaur', 'ivysaur'), ('venusaur', 'venusaur'), ('charmander', 'charmander'), ('charmeleon', 'charmeleon'), ('charizard', 'charizard'), ('squirtle', 'squirtle'), ('wartortle', 'wartortle'), ('blastoise', 'blastoise'), ('caterpie', 'caterpie'), ('metapod', 'metapod'), ('butterfree', 'butterfree'), ('weedle', 'weedle'), ('kakuna', 'kakuna'), ('beedrill', 'beedrill'), ('pidgey', 'pidgey'), ('pidgeotto', 'pidgeotto'), ('pidgeot', 'pidgeot'), ('rattata', 'rattata'), ('raticate', 'raticate')], max_length=200, null=True, verbose_name='opponent_pokemon_1'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='opponent_pokemon_2',
            field=models.CharField(choices=[('bulbasaur', 'bulbasaur'), ('ivysaur', 'ivysaur'), ('venusaur', 'venusaur'), ('charmander', 'charmander'), ('charmeleon', 'charmeleon'), ('charizard', 'charizard'), ('squirtle', 'squirtle'), ('wartortle', 'wartortle'), ('blastoise', 'blastoise'), ('caterpie', 'caterpie'), ('metapod', 'metapod'), ('butterfree', 'butterfree'), ('weedle', 'weedle'), ('kakuna', 'kakuna'), ('beedrill', 'beedrill'), ('pidgey', 'pidgey'), ('pidgeotto', 'pidgeotto'), ('pidgeot', 'pidgeot'), ('rattata', 'rattata'), ('raticate', 'raticate')], max_length=200, null=True, verbose_name='opponent_pokemon_2'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='opponent_pokemon_3',
            field=models.CharField(choices=[('bulbasaur', 'bulbasaur'), ('ivysaur', 'ivysaur'), ('venusaur', 'venusaur'), ('charmander', 'charmander'), ('charmeleon', 'charmeleon'), ('charizard', 'charizard'), ('squirtle', 'squirtle'), ('wartortle', 'wartortle'), ('blastoise', 'blastoise'), ('caterpie', 'caterpie'), ('metapod', 'metapod'), ('butterfree', 'butterfree'), ('weedle', 'weedle'), ('kakuna', 'kakuna'), ('beedrill', 'beedrill'), ('pidgey', 'pidgey'), ('pidgeotto', 'pidgeotto'), ('pidgeot', 'pidgeot'), ('rattata', 'rattata'), ('raticate', 'raticate')], max_length=200, null=True, verbose_name='opponent_pokemon_3'),
        ),
    ]
