# Generated by Django 2.2.19 on 2021-04-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_auto_20210324_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='creator_pokemon_1',
            field=models.CharField(max_length=200, null=True, verbose_name='creator_pokemon_1'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='creator_pokemon_2',
            field=models.CharField(max_length=200, null=True, verbose_name='creator_pokemon_2'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='creator_pokemon_3',
            field=models.CharField(max_length=200, null=True, verbose_name='creator_pokemon_3'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='opponent_pokemon_1',
            field=models.CharField(max_length=200, null=True, verbose_name='opponent_pokemon_1'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='opponent_pokemon_2',
            field=models.CharField(max_length=200, null=True, verbose_name='opponent_pokemon_2'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='opponent_pokemon_3',
            field=models.CharField(max_length=200, null=True, verbose_name='opponent_pokemon_3'),
        ),
    ]
