# Generated by Django 3.2 on 2021-04-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0003_auto_20210405_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
