# Generated by Django 3.2 on 2021-05-05 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battles', '0004_alter_battle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='creator_pokemon_1',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='creator_pokemon_2',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='creator_pokemon_3',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='opponent_pokemon_1',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='opponent_pokemon_2',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='opponent_pokemon_3',
        ),
        migrations.AddField(
            model_name='battle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_battles', to=settings.AUTH_USER_MODEL),
        ),
    ]
