# Generated by Django 3.2 on 2021-05-05 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battles', '0005_auto_20210505_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='battles.battle')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='pokemons.pokemon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battles.team')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('team', 'pokemon')},
            },
        ),
        migrations.AddField(
            model_name='team',
            name='pokemons',
            field=models.ManyToManyField(related_name='teams', through='battles.TeamPokemon', to='pokemons.Pokemon'),
        ),
        migrations.AddField(
            model_name='team',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
