# Generated by Django 3.2 on 2021-05-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0006_auto_20210505_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='pokemons',
        ),
    ]
