# Generated by Django 3.2 on 2021-05-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
        ('battles', '0007_remove_team_pokemons'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pokemons',
            field=models.ManyToManyField(related_name='teams', through='battles.TeamPokemon', to='pokemons.Pokemon'),
        ),
    ]
