# Generated by Django 3.2.2 on 2021-05-17 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battles', '0008_team_pokemons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
