# Generated by Django 3.2.2 on 2021-05-17 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battles', '0009_alter_battle_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_creator', to='users.user'),
        ),
    ]


# You are trying to change the nullable field 'creator' on battle to non-nullable without a default; we can't do that (the database needs something to populate existing rows).
# Please select a fix:
#  1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
#  2) Ignore for now, and let me handle existing rows with NULL myself (e.g. because you added a RunPython or RunSQL operation to handle NULL values in a previous data migration)
#  3) Quit, and let me add a default in models.py
# Select an option: 2
#
