# Generated by Django 3.2.6 on 2021-10-26 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0010_alter_battle_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampokemon',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='battles.team'),
        ),
    ]
