# Generated by Django 3.2.2 on 2021-05-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0010_alter_battle_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampokemon',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
