# Generated by Django 3.2 on 2021-05-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_id', models.IntegerField(verbose_name='PokeAPI ID')),
                ('name', models.CharField(max_length=50)),
                ('img_url', models.URLField(max_length=500)),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('hp', models.IntegerField()),
            ],
        ),
    ]
